## Pull the mysql image https://hub.docker.com/_/mysql
FROM mysql:5.7.30

## The maintainer name and email
MAINTAINER nadie <nadie@nunca.com>

# database = tareas_db and password for root = pass
ENV MYSQL_DATABASE=mysql \
    MYSQL_ROOT_PASSWORD=pass

EXPOSE 3306
